### ISSUE TITLE
Conda package is broken

### ISSUE THREAD

**Issue by st1553** [movingpictures83/KMerGenie#1]
Hello. Please fix the latest conda package. It seems to have an issue resolving the readfq dependency. Readfq exists in the conda environment so this should not be a problem as evidenced below. Thank you
Traceback (most recent call last):
  File "/miniforge/envs/myenv/bin/kmergenie", line 303, in <module>
    best_k = execute_once(arguments_passed_list, first_pass=first_pass)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniforge/envs/myenv/bin/kmergenie", line 279, in execute_once
    ntcard_wrapper(k_interval)
  File "/miniforge/envs/myenv/bin/kmergenie", line 221, in ntcard_wrapper
    max_read_length = get_read_length(read_file_list)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniforge/envs/myenv/bin/kmergenie", line 147, in get_read_length
    from readfq import readfq
ModuleNotFoundError: No module named 'readfq'

(myenv) [root@localhost home]$ readfq
Usage: readfq <in.seq>

**Comment by jiyonghao-cpu** [comment]
i have the same question
